import DivisorF.MandatoryCrossing
import DivisorF.CrossingPacking
import DivisorF.MultiplicityCorollaries
import DivisorF.CumulativeBoundary
import DivisorF.CumulativeCanonical
import DivisorF.GlobalSlack
import DivisorF.CumulativeLevels
import DivisorF.Rigidity
import DivisorF.TailMass
import DivisorF.TailLevels
import DivisorF.DefectSpectrum
import DivisorF.DefectSpectrumQuantiles
import DivisorF.DefectSpectrumEnvelope
import DivisorF.DefectSpectrumCorollaries
import DivisorF.DefectSpectrumUniformTransfers
import DivisorF.CubicExponentBarrier
import DivisorF.AsymptoticPrimeTransfer
import DivisorF.RegularEndpointTransfer
import DivisorF.WeightedRelativeDensity
import DivisorF.CubicDensityTransfer
import DivisorF.CubicNaturalDensity
import DivisorF.CubicNaturalMass
import DivisorF.CubicNaturalWeight
import DivisorF.Section6Assembly
import DivisorF.ExceptionalEndpointIntegerDiscretisation
import DivisorF.ExtremalBoundary
import DivisorF.ExtremalFibre
import DivisorF.ExtremalIncidence
import DivisorF.ExtremalContraction
import DivisorF.ExtremalRightComponents
import DivisorF.ExtremalRightCounting
import DivisorF.ExtremalLeafCounting
import DivisorF.ExtremalContractedIncidence
import DivisorF.ExtremalContractedGeometry
import DivisorF.ExtremalContractedEdgeCounting
import DivisorF.ExtremalContractedDegrees
import DivisorF.ExtremalContractedLeafCount
import DivisorF.ExtremalContractedPathLift
import DivisorF.ExtremalContractedAcyclic
import DivisorF.ExtremalContractedFinal
import DivisorF.ExtremalContractedTotalLeaves
import DivisorF.FiniteForestEuler
import DivisorF.ExtremalContractedComponents
import DivisorF.PathPartition
import DivisorF.PathForest
import DivisorF.DefectPathPartition
import DivisorF.ShortIntervalCones
import DivisorF.FactorizingPartition
import DivisorF.ShortIntervalTransfer
import DivisorF.VertexSensitivity
import DivisorF.CrossTypeTransport
import DivisorF.PrimeWindowBound
import DivisorF.UniformPointwiseBound
import DivisorF.BakerHarmanPintzCone

set_option linter.style.header false

/-! Axiom audit for the large-prime-fibre checkpoints.

The accepted criterion is that `sorryAx` never appears in the printed axioms of
any theorem below, and that no axiom outside Lean's standard three
(`propext`, `Classical.choice`, `Quot.sound`) is introduced. -/

#print axioms DivisorF.linearForestNumber_iso
#print axioms DivisorF.exists_maximumLinearForest
#print axioms DivisorF.distinct_fibres_anticomplete
#print axioms DivisorF.crossing_localization
#print axioms DivisorF.swapFibreVertex_involutive
#print axioms DivisorF.sameTypeFibreIso
#print axioms DivisorF.sameType_fibreDefect
#print axioms DivisorF.isAcyclic_sum
#print axioms DivisorF.linearForestNumber_induce_add_induce_le
#print axioms DivisorF.fibreIso
#print axioms DivisorF.fibreDefect_nonneg
#print axioms DivisorF.edgeCard_eq_internal_add_internal_add_crossing
#print axioms DivisorF.edgeCard_induce
#print axioms DivisorF.fibreDefect_eq_crossing_sub_losses
#print axioms DivisorF.fibreDefect_le_crossingCount
#print axioms DivisorF.fibreDefect_ge_crossing_sub_losses
#print axioms DivisorF.exists_crossing_minimizing_maximumLinearForest
#print axioms DivisorF.fibreDefect_eq_zero_iff_mandatoryCrossingCount_eq_zero
#print axioms DivisorF.fibreDefect_le_mandatoryCrossingCount
#print axioms DivisorF.crossingSlack_eq_restriction_losses
#print axioms DivisorF.restrictionLoss_sum_eq_of_crossing_minimizing
#print axioms DivisorF.fibreDefect_ge_iff_mandatoryCrossingCount_ge_crossingSlack_add
#print axioms DivisorF.fibreDefect_le_one_iff_mandatoryCrossingCount_le_crossingSlack_add_one
#print axioms DivisorF.universal_binary_iff_mandatoryCrossingCount_bound
#print axioms DivisorF.typePrimes_crossingCount_sum_le
#print axioms DivisorF.typeMultiplicity_mul_typeDefectNat_le
#print axioms DivisorF.typeDefect_eq_zero_of_large_multiplicity
#print axioms DivisorF.typeDefect_le_one_of_large_multiplicity
#print axioms DivisorF.typeDefectNat_le_multiplicity_floor
#print axioms DivisorF.paperTypeDefect_le_multiplicity_floor
#print axioms DivisorF.paperTypeMultiplicity_mul_typeDefect_le
#print axioms DivisorF.budgetForcesZero_iff
#print axioms DivisorF.budgetForcesBinary_iff
#print axioms DivisorF.exact_zero_threshold
#print axioms DivisorF.exact_binary_threshold
#print axioms DivisorF.mem_typePrimes_iff_quotient_interval
#print axioms DivisorF.typeMultiplicity_le_quotientIntervalWidth
#print axioms DivisorF.quotientIntervalWidth_le_ceil
#print axioms DivisorF.zero_defect_multiplicity_barrier
#print axioms DivisorF.binary_defect_multiplicity_barrier
#print axioms DivisorF.card_le_typeMultiplicity_of_same_type
#print axioms DivisorF.fibreDefect_eq_zero_of_type_multiplicity_lower_bound
#print axioms DivisorF.fibreDefect_le_one_of_type_multiplicity_lower_bound
#print axioms DivisorF.pointwise_zero_defect_transfer
#print axioms DivisorF.pointwise_binary_defect_transfer
#print axioms DivisorF.exact_quotient_width_identity
#print axioms DivisorF.same_type_of_quotient_interval_packet
#print axioms DivisorF.typeDefect_eq_zero_of_quotient_interval_packet
#print axioms DivisorF.fibreDefect_eq_zero_of_quotient_interval_packet
#print axioms DivisorF.zero_defect_transfer_from_decomposed_quotient_interval
#print axioms DivisorF.mem_weightedPairSpace
#print axioms DivisorF.weightedPairSpace_card
#print axioms DivisorF.badEndpointPairSpace_card
#print axioms DivisorF.positiveDefectWeightedPairs_card_le_bad_weight
#print axioms DivisorF.positiveDefectWeightedPairs_card_le_bad_card_mul
#print axioms DivisorF.paperTypeDefect_eq_zero_of_prime_rich_range
#print axioms DivisorF.eventuallyZeroDefectOn_of_eventuallyPrimeRich
#print axioms DivisorF.EventuallyZeroDefectOn.mono
#print axioms DivisorF.genericPowerConeTransfer_interface
#print axioms DivisorF.naturalPowerCone_eventuallyContained_quotientPowerRange
#print axioms DivisorF.eventuallyZeroDefectOn_powerCone_of_fixedExponentWindow
#print axioms DivisorF.eventuallyZeroDefectOn_naturalPowerCone_of_fixedExponentPrimeRich
#print axioms DivisorF.paperTypeDefect_eq_zero_of_prime_packet_subset
#print axioms DivisorF.endpointPairSpace_zero_of_common_prime_packet
#print axioms DivisorF.positiveDefectWeightedPairs_card_le_bad_card_mul_of_common_packets
#print axioms DivisorF.weightedRelativeDensityZero_of_negligible_bad_endpoints
#print axioms DivisorF.positiveDefectWeightedPairs_card_mul_le_total
#print axioms DivisorF.cubicEndpointExponent_lt_half
#print axioms DivisorF.endpointCoreContainedInNaturalCone_cubic
#print axioms DivisorF.eventuallySuccEndpointPowerAbsorbed_of_lt
#print axioms DivisorF.eventuallyNaturalConeContainedInEndpointCone_cubic
#print axioms DivisorF.cubicDensityRangePackage
#print axioms DivisorF.mem_cubicNaturalPairSpace
#print axioms DivisorF.eventuallyZeroOutsideBadEndpointsNatural_of_endpoint_cutoff
#print axioms DivisorF.positiveDefectCubicNaturalPairs_card_le_bad_card_mul
#print axioms DivisorF.eventuallyNegligibleCubicNaturalBadBurden_of_sparse_bad_endpoints
#print axioms DivisorF.cubicNaturalRelativeDensityZero_of_sparse_bad_endpoints
#print axioms DivisorF.cubicNaturalPairSpace_card_lower_of_core_cutoff
#print axioms DivisorF.eventuallyCubicNaturalTotalWeightLower_canonical
#print axioms DivisorF.cubicNaturalRelativeDensityZero_of_sparse_bad_endpoints_canonical
#print axioms DivisorF.two_mul_endpointPairWeight_eq
#print axioms DivisorF.endpointPairWeight_le_mul_of_cutoff_le_mul
#print axioms DivisorF.eventuallyCubicNaturalCutoffComparison_three
#print axioms DivisorF.eventuallyCubicNaturalEndpointWeightBound_canonical
#print axioms DivisorF.cubicNaturalRelativeDensityZero_of_sparse_bad_endpoints_cubicScale
#print axioms DivisorF.paperTypeDefect_le_one_of_effective_packing
#print axioms DivisorF.paperTypeDefect_eq_zero_of_effective_packing
#print axioms DivisorF.paperTypeDefect_le_one_of_effective_nat_threshold
#print axioms DivisorF.paperTypeDefect_eq_zero_of_effective_nat_threshold
#print axioms DivisorF.exists_eventual_zero_threshold_for_fixed_type
#print axioms DivisorF.nonbinary_type_below_effective_threshold
#print axioms DivisorF.typePrimeValues_eq_quotientIntervalPrimeValues
#print axioms DivisorF.typeMultiplicity_eq_quotientIntervalPrimeValues_card
#print axioms DivisorF.paperTypeDefect_eq_zero_of_quotient_prime_count
#print axioms DivisorF.paperTypeDefect_le_one_of_quotient_prime_count
#print axioms DivisorF.occupied_type_sq_le
#print axioms DivisorF.le_realCubeRoot_of_threshold
#print axioms DivisorF.binary_cubic_exponent_ceiling
#print axioms DivisorF.zero_cubic_exponent_ceiling
#print axioms DivisorF.sum_typePrimes_fibreDefect_eq_paperTypeContribution
#print axioms DivisorF.cumulativeDefectSum_eq_paperTypeContributionSum
#print axioms DivisorF.paperCumulativeBoundaryBudget
#print axioms DivisorF.cumulativeCrossingMass_le
#print axioms DivisorF.cumulativeDefectSum_le
#print axioms DivisorF.globalBoundarySlackIdentity
#print axioms DivisorF.cumulativeLevel_card_le
#print axioms DivisorF.cumulativeNonbinary_card_le
#print axioms DivisorF.cumulativeDefectSum_decomposition
#print axioms DivisorF.nonbinaryStabilityIdentity
#print axioms DivisorF.extremalRigidity_terms_vanish
#print axioms DivisorF.fibreDefect_eq_two_of_extremal
#print axioms DivisorF.nearExtremalRigidityIdentity
#print axioms DivisorF.tailEndpointVertices_card_eq
#print axioms DivisorF.crossingFinset_subset_tailEndpoint_incidence
#print axioms DivisorF.tailDefectSum_le
#print axioms DivisorF.tailLevel_card_le
#print axioms DivisorF.positiveDefectTail_card_le
#print axioms DivisorF.defectLevelPrimes_eq_head_union_tail
#print axioms DivisorF.defectLevelPrimes_card_eq_head_add_tail
#print axioms DivisorF.defectSpectrum_le_variational
#print axioms DivisorF.sqrt_lt_largePrime_val
#print axioms DivisorF.tailEndpointCount_sqrt_eq
#print axioms DivisorF.defectSpectrum_le_high_level
#print axioms DivisorF.tailEndpointCount_cast_le_div
#print axioms DivisorF.defectSpectrum_real_le_variational_relaxed
#print axioms DivisorF.defectSpectrum_real_le_of_prefix_bound
#print axioms DivisorF.defectSpectrum_le_high_level_real
#print axioms DivisorF.defectThreshold_le_linear_quantile
#print axioms DivisorF.mem_defectLevelPrimes_one_iff_positive
#print axioms DivisorF.mem_defectLevelPrimes_two_iff_nonbinary
#print axioms DivisorF.positiveDefectPrimes_card_eq_spectrum_one
#print axioms DivisorF.nonbinaryDefectPrimes_card_eq_spectrum_two
#print axioms DivisorF.positiveDefectSupport_real_le_of_spectrum_one_bound
#print axioms DivisorF.nonbinaryDefectSupport_real_le_of_spectrum_two_bound
#print axioms DivisorF.fibreDefectNat_le_two_mul_N
#print axioms DivisorF.defectThreshold_le_two_mul_N_of_spectrum_pos
#print axioms DivisorF.le_orderedDefect_iff_spectrum_count
#print axioms DivisorF.orderedDefect_pos_iff
#print axioms DivisorF.orderedDefect_le_linear_quantile
#print axioms DivisorF.defectThreshold_le_log_of_bulk
#print axioms DivisorF.defectThreshold_le_quadratic_of_spectrum_bound
#print axioms DivisorF.defectThreshold_le_quadratic_of_bulk_low_bound
#print axioms DivisorF.orderedDefect_le_quadratic_of_bulk_low_bound
#print axioms DivisorF.variational_tail_eq_balanced_term
#print axioms DivisorF.defectSpectrum_real_le_balanced_of_prefix_bound
#print axioms DivisorF.defectSpectrumBalanceQ_sq
#print axioms DivisorF.defectSpectrumBalanceQ_div_log
#print axioms DivisorF.defectSpectrum_real_le_low_of_balanced_prefix_bound
#print axioms DivisorF.defectSpectrum_real_le_uniform_envelope
#print axioms DivisorF.lowSpectrum_sqrt_ratio_eq_normalized
#print axioms DivisorF.defectSpectrum_real_le_uniform_envelope_of_low_sqrt_bound
#print axioms DivisorF.defectSpectrum_real_le_fixed_of_balanced_prefix
#print axioms DivisorF.positiveDefectSupport_real_le_fixed_of_balanced_prefix
#print axioms DivisorF.nonbinaryDefectSupport_real_le_fixed_of_balanced_prefix
#print axioms DivisorF.positiveDefectSupport_real_le_of_uniform_low
#print axioms DivisorF.positiveDefectRelativeDensity_le_of_bounds
#print axioms DivisorF.positiveDefectRelativeDensity_le_pnt_scale
#print axioms DivisorF.defectSpectrum_uniform_low_of_balanced_prefix_input
#print axioms DivisorF.exists_uniform_defect_spectrum_envelope_of_balanced_prefix_input
#print axioms DivisorF.exists_orderedDefect_quadratic_bulk_constants_of_balanced_prefix_input
#print axioms DivisorF.smallEndpointVertices_card_eq
#print axioms DivisorF.cumulativeCrossingMass_eq_capacity_of_extremal
#print axioms DivisorF.incidentEdges_eq_cumulativeCrossingUnion_of_extremal
#print axioms DivisorF.selectedDegree_eq_two_on_boundary_of_extremal
#print axioms DivisorF.restrictionLosses_eq_zero_of_extremal
#print axioms DivisorF.crossingCount_eq_fibreDefect_of_extremal
#print axioms DivisorF.fibreDefect_eq_zero_or_two_of_extremal
#print axioms DivisorF.crossingCount_eq_zero_or_two_of_extremal
#print axioms DivisorF.crossingCount_eq_two_of_extremal
#print axioms DivisorF.crossingCount_eq_zero_of_not_nonbinary_extremal
#print axioms DivisorF.crossingFinset_eq_empty_of_not_nonbinary_extremal
#print axioms DivisorF.cumulativeCrossingUnion_eq_nonbinaryCrossingUnion_of_extremal
#print axioms DivisorF.incidentEdges_eq_nonbinaryCrossingUnion_of_extremal
#print axioms DivisorF.card_crossingFinset_eq_two_of_extremal
#print axioms DivisorF.exists_nonbinary_fibre_for_boundary_edge_of_extremal
#print axioms DivisorF.unique_nonbinary_fibre_for_boundary_edge_of_extremal
#print axioms DivisorF.extremalCutGraph_isAcyclic
#print axioms DivisorF.boundary_isolated_in_extremalCutGraph
#print axioms DivisorF.extremalRestrictionComponent_boundary_eq_iff
#print axioms DivisorF.extremalRestrictionComponent_ne_of_two_attachments
#print axioms DivisorF.crossing_mem_nonbinaryCrossingUnion
#print axioms DivisorF.nonbinary_attachment_components_distinct
#print axioms DivisorF.activeFibreRestrictionComponent_nonempty_of_extremal
#print axioms DivisorF.activeFibreRestrictionComponent_card_eq_one_or_two_of_extremal
#print axioms DivisorF.sum_activeFibreRestrictionComponentCount_eq_boundary_add_split
#print axioms DivisorF.totalActiveRightLeafCount_eq_two_mul_split
#print axioms DivisorF.extremalContractedVertexCount_eq
#print axioms DivisorF.extremalContractedVertexCount_sub_edgeCount_eq_split
#print axioms DivisorF.extremalContractedIncidenceGraph_adj_cases
#print axioms DivisorF.extremalRightNode_card_eq_boundary_add_split
#print axioms DivisorF.extremalContractedIncidenceGraph_vertex_card_eq
#print axioms DivisorF.crossingOutsideEndpoint_value_le_quotientType
#print axioms DivisorF.extremalContractedIncidenceGraph_adj_of_crossing
#print axioms DivisorF.extremalBoundaryNode_not_inFibre_of_sq_le
#print axioms DivisorF.boundaryNode_eq_crossingBoundaryNode_of_mem
#print axioms DivisorF.crossing_eq_outside_fibre_endpoints
#print axioms DivisorF.fibreCrossingEdge_eq_of_same_contracted_nodes
#print axioms DivisorF.extremalContractedIncidenceGraph_crossing_witness_unique
#print axioms DivisorF.extremalNonbinaryCrossingToContractedEdge_injective
#print axioms DivisorF.extremalNonbinaryCrossingToContractedEdge_surjective
#print axioms DivisorF.extremalNonbinaryCrossingEdge_card_eq
#print axioms DivisorF.extremalContractedIncidenceGraph_edgeCard_eq
#print axioms DivisorF.rightNodeCrossingSet_ncard_eq_selectedDegree
#print axioms DivisorF.extremalRightNode_selectedDegree_eq_two_of_one_component
#print axioms DivisorF.extremalRightNode_selectedDegree_eq_one_of_two_components
#print axioms DivisorF.extremalRightNode_selectedDegree_eq_one_or_two
#print axioms DivisorF.extremalRightNode_selectedDegree_eq_one_iff_split
#print axioms DivisorF.extremalContractedIncidenceGraph_isBipartiteWith
#print axioms DivisorF.extremalContractedRightPart_sum_selectedDegree_eq_edgeCard
#print axioms DivisorF.extremalContractedRightPart_card_eq_boundary_add_split
#print axioms DivisorF.extremalContractedRightLeaves_card_eq_two_mul_split
#print axioms DivisorF.crossingOutsideEndpoint_adj_crossingFibreEndpoint
#print axioms DivisorF.crossingFibreEndpoints_reachable_cut_of_same_activeComponent
#print axioms DivisorF.exists_crossing_witness_of_contracted_adj
#print axioms DivisorF.original_reachable_of_common_contracted_right
#print axioms DivisorF.exists_cut_reachable_endpoints_of_common_contracted_right
#print axioms DivisorF.extremalNonbinaryCrossing_isBridge
#print axioms DivisorF.not_reachable_delete_crossing_outside_fibre
#print axioms DivisorF.extremalNonbinaryCrossingEdge_eq_of_edge_eq
#print axioms DivisorF.contractedSideOfCrossing_of_reachable_delete_target
#print axioms DivisorF.extremalNonbinaryCrossingToContractedEdge_isBridge
#print axioms DivisorF.extremalContractedIncidenceGraph_isAcyclic
#print axioms DivisorF.edgeCard_lt_fintypeCard_of_isAcyclic
#print axioms DivisorF.one_le_splitNonbinaryFibreCount_of_extremal
#print axioms DivisorF.one_le_splitNonbinaryFibreCount_of_extremal_le_sqrt
#print axioms DivisorF.extremalContractedIncidence_summary
#print axioms DivisorF.extremalLeftNodeCrossingSet_ncard_eq_selectedDegree
#print axioms DivisorF.extremalBoundaryNode_contractedDegree_eq_two
#print axioms DivisorF.extremalContractedLeaves_eq_rightLeaves
#print axioms DivisorF.extremalContractedLeaves_card_eq_two_mul_split
#print axioms DivisorF.card_connectedComponent_add_edgeCard_eq_fintypeCard
#print axioms DivisorF.extremalContractedIncidenceGraph_connectedComponent_card_eq_split
#print axioms DivisorF.extremalContractedIncidence_corollary
#print axioms DivisorF.extremalContractedIncidence_corollary_le_sqrt

-- Section 6: integer discretisation, packet threshold, and same-family assembly.
#print axioms DivisorF.integerDiscretisationCore_of_manuscript
#print axioms DivisorF.concreteTranslatedEndpointPrimePacket_zeroThreshold_of_card_gt_twice_cutoff
#print axioms DivisorF.eventuallyConcreteTranslatedEndpointData_powerCutoff_of_packetDominates
#print axioms DivisorF.eventuallyZeroOutsideBadEndpoints_powerCutoff_of_packetDominates
#print axioms DivisorF.section6TranslatedBadEndpoints_sparse_of_fixedPrecision
#print axioms DivisorF.section6ZeroOutsideTranslatedBadEndpoints_of_packetDominates
#print axioms DivisorF.section6RegularEndpointPackage_of_fixedPrecision_and_packetDominates

#print axioms DivisorF.exists_isHamiltonian_of_connected_degree_le_two
#print axioms DivisorF.isPathBlock_component_supp
#print axioms DivisorF.isPathPartition_componentSupports
#print axioms DivisorF.pathPartitionNumber_add_linearForestNumber_le
#print axioms DivisorF.walkGraph_isAcyclic
#print axioms DivisorF.walkGraph_selectedDegree_le_two
#print axioms DivisorF.isAcyclic_sup_of_disjoint_support
#print axioms DivisorF.exists_linearForest_of_pathBlocks
#print axioms DivisorF.le_pathPartitionNumber_add_linearForestNumber
#print axioms DivisorF.pathPartitionNumber_add_linearForestNumber
#print axioms DivisorF.card_inFibre
#print axioms DivisorF.fibreDefect_eq_pathPartitionForm
#print axioms DivisorF.coneExponent_guthMaynard
#print axioms DivisorF.coneExponent_li
#print axioms DivisorF.exists_beta_of_lt_third
#print axioms DivisorF.eventuallyZeroDefect_guthMaynard_cone
#print axioms DivisorF.eventuallyZeroDefect_li_cone
#print axioms DivisorF.eventuallyZeroDefect_riemann_cone
#print axioms DivisorF.pathPartitionNumber_iso
#print axioms DivisorF.splitPartitionNumber_eq
#print axioms DivisorF.factorizingPartitionNumber_eq
#print axioms DivisorF.fibreDefect_eq_factorizationPenalty
#print axioms DivisorF.fibreDefect_eq_zero_iff_exists_factorizing_optimum
#print axioms DivisorF.primeCounting_add_card_filter_Ioc
#print axioms DivisorF.eventually_transfer_conditions
#print axioms DivisorF.shortIntervalQuotientRichness
#print axioms DivisorF.eventuallyZeroDefectOn_quotientPowerRange_of_shortInterval
#print axioms DivisorF.eventuallyZeroDefectOn_naturalPowerCone_of_shortInterval
#print axioms DivisorF.eventuallyZeroDefect_guthMaynard_cone_of_shortInterval
#print axioms DivisorF.eventuallyZeroDefect_li_cone_of_shortInterval
#print axioms DivisorF.eventuallyZeroDefect_riemann_cone_of_shortInterval

-- Section 5 of the 10 September 2026 manuscript: vertex sensitivity,
-- cross-type transport, the prime-window bound and the uniform pointwise bound.
#print axioms DivisorF.card_incidentEdgeFinset_le_two_mul
#print axioms DivisorF.internalCard_add_crossingCard_le_two_mul
#print axioms DivisorF.linearForestNumber_le_induce_add_two_mul
#print axioms DivisorF.linearForestNumber_induce_le
#print axioms DivisorF.vertexSensitivity_linearForestNumber
#print axioms DivisorF.vertexSensitivity_pathPartitionNumber
#print axioms DivisorF.divisorGraphTruncIso
#print axioms DivisorF.card_divisorGraphTrunc_complement
#print axioms DivisorF.abs_divisorPathPartitionNumber_sub_le
#print axioms DivisorF.quotientType_le_of_val_le
#print axioms DivisorF.quotientType_lt_val
#print axioms DivisorF.truncToComplement_injective
#print axioms DivisorF.truncToComplement_surjective
#print axioms DivisorF.truncToComplement_adj_iff
#print axioms DivisorF.truncatedComplementIso
#print axioms DivisorF.card_truncDeleted_le
#print axioms DivisorF.abs_complement_pathPartitionNumber_sub_le
#print axioms DivisorF.crossTypeTransport
#print axioms DivisorF.crossTypeDefectLipschitz
#print axioms DivisorF.fibreDefect_le_two_mul_pred
#print axioms DivisorF.fibreDefect_eq_zero_of_quotientType_le_one
#print axioms DivisorF.window_fibreDefect_lower_bound
#print axioms DivisorF.window_defect_sum_le
#print axioms DivisorF.fibreDefect_le_window_bound
#print axioms DivisorF.primeWindow_card_eq_succ_card_Ioc
#print axioms DivisorF.primeWindowBound
#print axioms DivisorF.log_le_twenty_mul_rpow
#print axioms DivisorF.log_div_rpow_le
#print axioms DivisorF.delta_le_of_two_le
#print axioms DivisorF.fibreDefect_le_explicit_of_bhp
#print axioms DivisorF.fibreDefect_le_uniform_of_bhp
#print axioms DivisorF.fibreDefect_le_quotient_power_of_bhp
#print axioms DivisorF.fibreDefect_le_ambient_power_of_bhp

-- Section 6 of the 10 September 2026 manuscript, at the Baker--Harman--Pintz
-- exponent: the cone `19/59` and its fixed-type corollary.
#print axioms DivisorF.coneExponent_bakerHarmanPintz
#print axioms DivisorF.exists_beta_of_lt_bhp
#print axioms DivisorF.eventuallyZeroDefect_bakerHarmanPintz_cone_of_shortInterval
#print axioms DivisorF.fibreDefect_eq_zero_of_cone_and_prime_lower
#print axioms DivisorF.paperTypeDefect_eq_zero_of_le_one
#print axioms DivisorF.eventuallyZeroDefect_fixedType_of_cone
#print axioms DivisorF.eventuallyZeroDefect_fixedType_of_shortInterval
