import DivisorF.ExceptionalEndpointThickeningGeometry
import Mathlib.Tactic

set_option linter.style.header false

/-!
# Shift stability for the exceptional-endpoint discretisation

This module formalizes the project-owned logical core of the shift argument in
Lemma 6.1.  The external almost-all theorem supplies a small real exceptional
set.  The manuscript then proves that if an integer centre is bad at relative
error `delta`, every sufficiently close real point remains bad at relative
error `delta / 2`.

We isolate exactly the two quantitative estimates used in that step:

* the interval statistic changes by at most `delta / 8` of the centre scale;
* the main term changes by at most `delta / 8` of the centre scale.

Together with the harmless local scale comparison `M(u) <= 3/2 M(n)`, these
bounds force half-error badness throughout the whole thickening interval.  In
the manuscript, the first two estimates are supplied by the symmetric-
difference bound for the von Mangoldt interval and the elementary variation of
`x^eta`; no published prime theorem is proved here.
-/

namespace DivisorF

/-- Relative-error badness for a real-valued interval statistic `A` with main
term `M`.  This is the abstract form of
`|Psi_eta(x) - x^eta| > delta * x^eta` used in Lemma 6.1. -/
def RealRelativeBad
    (A M : ℝ → ℝ) (delta x : ℝ) : Prop :=
  delta * M x < |A x - M x|

/-- A bad centre remains bad at half the relative error once the total change
of the centred error is at most one quarter of the centre tolerance and the
main term at the nearby point is at most `3/2` of the centre main term. -/
theorem realRelativeBad_half_of_error_shift
    {A M : ℝ → ℝ} {delta n u : ℝ}
    (hdelta : 0 ≤ delta)
    (_hMn : 0 ≤ M n)
    (hbad : RealRelativeBad A M delta n)
    (hshift :
      |(A n - M n) - (A u - M u)| ≤ (delta / 4) * M n)
    (hscale : M u ≤ (3 / 2 : ℝ) * M n) :
    RealRelativeBad A M (delta / 2) u := by
  rw [RealRelativeBad] at hbad ⊢
  have htri :
      |A n - M n| ≤
        |(A n - M n) - (A u - M u)| + |A u - M u| := by
    calc
      |A n - M n| = |((A n - M n) - (A u - M u)) + (A u - M u)| := by
        congr 1
        ring
      _ ≤ |(A n - M n) - (A u - M u)| + |A u - M u| := abs_add_le _ _
  have hlower :
      (3 * delta / 4) * M n < |A u - M u| := by
    linarith
  have hdelta2 : 0 ≤ delta / 2 := by positivity
  have hscale' :
      (delta / 2) * M u ≤ (delta / 2) * ((3 / 2 : ℝ) * M n) :=
    mul_le_mul_of_nonneg_left hscale hdelta2
  have hrewrite :
      (delta / 2) * ((3 / 2 : ℝ) * M n) =
        (3 * delta / 4) * M n := by
    ring
  rw [hrewrite] at hscale'
  exact lt_of_le_of_lt hscale' hlower

/-- Separate control of the statistic and main term implies the quarter-error
shift bound used by `realRelativeBad_half_of_error_shift`.  This mirrors the
manuscript's two estimates: symmetric-difference control for `Psi_eta` and
variation control for `x^eta`. -/
theorem error_shift_le_quarter_of_two_eighth_bounds
    {A M : ℝ → ℝ} {delta n u : ℝ}
    (hA : |A n - A u| ≤ (delta / 8) * M n)
    (hM : |M n - M u| ≤ (delta / 8) * M n) :
    |(A n - M n) - (A u - M u)| ≤ (delta / 4) * M n := by
  have hrewrite :
      (A n - M n) - (A u - M u) =
        (A n - A u) - (M n - M u) := by
    ring
  rw [hrewrite]
  calc
    |(A n - A u) - (M n - M u)|
        ≤ |A n - A u| + |M n - M u| := abs_sub _ _
    _ ≤ (delta / 8) * M n + (delta / 8) * M n :=
      add_le_add hA hM
    _ = (delta / 4) * M n := by ring

/-- Quantitative shift data on every thickening interval generated by a finite
set of bad integer centres.  These are exactly the project-owned local
estimates immediately preceding the Lebesgue double count in Lemma 6.1. -/
structure IntegerExceptionalShiftData
    (bad : Finset ℕ) (H : ℕ)
    (A M : ℝ → ℝ) (delta : ℝ) where
  delta_nonneg : 0 ≤ delta
  main_nonneg : ∀ n ∈ bad, 0 ≤ M (n : ℝ)
  badAtCentre : ∀ n ∈ bad, RealRelativeBad A M delta (n : ℝ)
  statisticShift : ∀ n ∈ bad, ∀ u ∈ integerThickeningInterval n H,
    |A (n : ℝ) - A u| ≤ (delta / 8) * M (n : ℝ)
  mainShift : ∀ n ∈ bad, ∀ u ∈ integerThickeningInterval n H,
    |M (n : ℝ) - M u| ≤ (delta / 8) * M (n : ℝ)
  localScale : ∀ n ∈ bad, ∀ u ∈ integerThickeningInterval n H,
    M u ≤ (3 / 2 : ℝ) * M (n : ℝ)

/-- **Lemma 6.1 whole-interval stability transfer.**

The manuscript-shaped shift estimates imply that every point in the thickening
of a bad integer lies in the half-error real exceptional set. -/
theorem IntegerExceptionalShiftData.bad_half_on_interval
    {bad : Finset ℕ} {H : ℕ}
    {A M : ℝ → ℝ} {delta : ℝ}
    (data : IntegerExceptionalShiftData bad H A M delta)
    {n : ℕ} (hn : n ∈ bad)
    {u : ℝ} (hu : u ∈ integerThickeningInterval n H) :
    RealRelativeBad A M (delta / 2) u := by
  apply realRelativeBad_half_of_error_shift
      data.delta_nonneg (data.main_nonneg n hn) (data.badAtCentre n hn)
  · exact error_shift_le_quarter_of_two_eighth_bounds
      (data.statisticShift n hn u hu) (data.mainShift n hn u hu)
  · exact data.localScale n hn u hu

/-- The shift-stability package constructs the literal interval-containment
object consumed by the Lebesgue layer, with the exceptional set exactly the
half-error bad set.  Thus `LiteralIntegerThickening.intervalSubset` is no longer
an independent assumption once the manuscript's two local shift estimates are
available. -/
def IntegerExceptionalShiftData.toLiteralIntegerThickening
    {bad : Finset ℕ} {H : ℕ}
    {A M : ℝ → ℝ} {delta : ℝ}
    (data : IntegerExceptionalShiftData bad H A M delta) :
    LiteralIntegerThickening bad H where
  exceptionalSet := {u : ℝ | RealRelativeBad A M (delta / 2) u}
  intervalSubset := by
    intro n hn u hu
    exact data.bad_half_on_interval hn hu

/-- Pointwise form of the preceding constructor: the whole literal union of
bad-centre intervals lies in the half-error exceptional set. -/
theorem IntegerExceptionalShiftData.union_subset_halfError
    {bad : Finset ℕ} {H : ℕ}
    {A M : ℝ → ℝ} {delta : ℝ}
    (data : IntegerExceptionalShiftData bad H A M delta) :
    (⋃ n ∈ bad, integerThickeningInterval n H) ⊆
      {u : ℝ | RealRelativeBad A M (delta / 2) u} := by
  intro u hu
  rcases Set.mem_iUnion.mp hu with ⟨n, hu⟩
  rcases Set.mem_iUnion.mp hu with ⟨hn, hu⟩
  exact data.bad_half_on_interval hn hu

end DivisorF
